General:
      Measurement: "higgs_tautau_signal_strength"
      POI: "mu_htautau"
      

Samples:
    - Name              : htautau
      Tree              : tree_htautau
      SamplePath        : saved_datasets/dataset_nominal.root
      Weight            : weights
      UseAsReference    : True
      UseAsBasis        : True

    - Name              : ttbar
      Tree              : tree_ttbar
      SamplePath        : saved_datasets/dataset_nominal.root
      Weight            : weights
      UseAsReference    : True
      UseAsBasis        : True
        
    - Name : ztautau
      Tree              : tree_ztautau
      SamplePath        : saved_datasets/dataset_nominal.root
      Weight            : weights
      UseAsReference    : False
      UseAsBasis        : True

NormFactors:
  - Name: "mu_htautau"
    Samples: "htautau"
    Nominal: 1
    Bounds: [0, 10]
  - Name: "mu_ztautau"
    Samples: "ztautau"
    Nominal: 1
    Bounds: [0, 10]
  - Name: "mu_ttbar"
    Samples: "ttbar"
    Nominal: 1
    Bounds: [0, 10]
    
Systematics:
    -   Name                : JES
        Type                : NormPlusShape
        Samples             : 
              - htautau
              - ztautau
              - ttbar
        Up                  : 
            -   SampleName        : htautau
                Path              : saved_datasets/dataset_JES_up.root
                Tree              : tree_htautau
                Weight            : weights
            -   SampleName        : ztautau
                Path              : saved_datasets/dataset_JES_up.root
                Tree              : tree_ztautau
                Weight            : weights
            -   SampleName        : ttbar
                Path              : saved_datasets/dataset_JES_up.root
                Tree              : tree_ttbar
                Weight            : weights
        Dn                  :
            -   SampleName        : htautau
                Path              : saved_datasets/dataset_JES_dn.root
                Tree              : tree_htautau
                Weight            : weights
            -   SampleName        : ztautau
                Path              : saved_datasets/dataset_JES_dn.root
                Tree              : tree_ztautau
                Weight            : weights
            -   SampleName        : ttbar
                Path              : saved_datasets/dataset_JES_dn.root
                Tree              : tree_ttbar
                Weight            : weights
    -   Name                : TES
        Type                : NormPlusShape
        Samples             : 
              - htautau
              - ztautau
              - ttbar
        Up                  :
            -   SampleName        : htautau
                Path              : saved_datasets/dataset_TES_up.root
                Tree              : tree_htautau
                Weight            : weights
            -   SampleName        : ztautau
                Path              : saved_datasets/dataset_TES_up.root
                Tree              : tree_ztautau
                Weight            : weights
            -   SampleName        : ttbar
                Path              : saved_datasets/dataset_TES_up.root
                Tree              : tree_ttbar
                Weight            : weights
        Dn                  :
            -   SampleName        : htautau
                Path              : saved_datasets/dataset_TES_dn.root
                Tree              : tree_htautau
                Weight            : weights
            -   SampleName        : ztautau
                Path              : saved_datasets/dataset_TES_dn.root
                Tree              : tree_ztautau
                Weight            : weights
            -   SampleName        : ttbar
                Path              : saved_datasets/dataset_TES_dn.root
                Tree              : tree_ttbar
                Weight            : weights


TrainingFeatures:
    - DER_mass_transverse_met_lep
    - log_DER_mass_vis
    - log_DER_pt_h
    - DER_deltar_had_lep
    - log_DER_pt_tot
    - log_DER_sum_pt
    - DER_pt_ratio_lep_had
    - DER_met_phi_centrality
    
TrainingFeaturesToStandardize:
    - DER_mass_transverse_met_lep
    - log_DER_mass_vis
    - log_DER_pt_h
    - DER_deltar_had_lep
    - log_DER_pt_tot
    - log_DER_sum_pt
    - DER_pt_ratio_lep_had
    - DER_met_phi_centrality

Regions:
-   Name: CR
    Filter: presel_score<-1.0
    Variable: presel_score
    Type: binned
    Binning:
        - -8.747320175170898
        - -6.810490310192108
        - -4.873660445213318
        - -2.9368305802345276
        - -1.0000007152557373
-   Name: SR_binned
    Filter: presel_score>4.5
    Variable: presel_score
    Type: binned
    Binning:
        - 4.500021934509277
        - 5.942246437072754
-   Name: SR
    Filter: presel_score>=-1.0 & presel_score<=4.5
    Variable: null
    Type: unbinned
    Binning: null
    TrainedModels:
        - Nominal       :
            -   SampleName: htautau
                Models: /home/jsandesara_umass_edu/NSBI-workflow-tutorial/FAIR_universe_Higgs_tautau/saved_data/output_training_nominal/output_model_params_htautau/
            -   SampleName: ttbar
                Models: /home/jsandesara_umass_edu/NSBI-workflow-tutorial/FAIR_universe_Higgs_tautau/saved_data/output_training_nominal/output_model_params_ttbar/
            -   SampleName: ztautau
                Models: /home/jsandesara_umass_edu/NSBI-workflow-tutorial/FAIR_universe_Higgs_tautau/saved_data/output_training_nominal/output_model_params_ztautau/
        - Systematics       :
            -   SystName: TES
            -   Samples         :
                -   SampleName: htautau
                    ModelsUp: /home/jsandesara_umass_edu/NSBI-workflow-tutorial/FAIR_universe_Higgs_tautau/saved_data/output_training_systematics/output_model_params_htautau_TES_Up/
                    ModelsDn: /home/jsandesara_umass_edu/NSBI-workflow-tutorial/FAIR_universe_Higgs_tautau/saved_data/output_training_systematics/output_model_params_htautau_TES_Dn/
                -   SampleName: ztautau
                    ModelsUp: /home/jsandesara_umass_edu/NSBI-workflow-tutorial/FAIR_universe_Higgs_tautau/saved_data/output_training_systematics/output_model_params_ztautau_TES_Up/
                    ModelsDn: /home/jsandesara_umass_edu/NSBI-workflow-tutorial/FAIR_universe_Higgs_tautau/saved_data/output_training_systematics/output_model_params_ztautau_TES_Dn/
                -   SampleName: ttbar
                    ModelsUp: /home/jsandesara_umass_edu/NSBI-workflow-tutorial/FAIR_universe_Higgs_tautau/saved_data/output_training_systematics/output_model_params_ttbar_TES_Up/
                    ModelsDn: /home/jsandesara_umass_edu/NSBI-workflow-tutorial/FAIR_universe_Higgs_tautau/saved_data/output_training_systematics/output_model_params_ttbar_TES_Dn/
            -   SystName: JES
            -   Samples         :
                -   SampleName: htautau
                    ModelsUp: /home/jsandesara_umass_edu/NSBI-workflow-tutorial/FAIR_universe_Higgs_tautau/saved_data/output_training_systematics/output_model_params_htautau_JES_Up/
                    ModelsDn: /home/jsandesara_umass_edu/NSBI-workflow-tutorial/FAIR_universe_Higgs_tautau/saved_data/output_training_systematics/output_model_params_htautau_JES_Dn/
                -   SampleName: ztautau
                    ModelsUp: /home/jsandesara_umass_edu/NSBI-workflow-tutorial/FAIR_universe_Higgs_tautau/saved_data/output_training_systematics/output_model_params_ztautau_JES_Up/
                    ModelsDn: /home/jsandesara_umass_edu/NSBI-workflow-tutorial/FAIR_universe_Higgs_tautau/saved_data/output_training_systematics/output_model_params_ztautau_JES_Dn/
                -   SampleName: ttbar
                    ModelsUp: /home/jsandesara_umass_edu/NSBI-workflow-tutorial/FAIR_universe_Higgs_tautau/saved_data/output_training_systematics/output_model_params_ttbar_JES_Up/
                    ModelsDn: /home/jsandesara_umass_edu/NSBI-workflow-tutorial/FAIR_universe_Higgs_tautau/saved_data/output_training_systematics/output_model_params_ttbar_JES_Dn/

