PATH_PREFIX: /home/jsandesara_umass_edu/NSBI-workflow-tutorial/FAIR_universe_Higgs_tautau/
PATH_SAVED_DATA: /home/jsandesara_umass_edu/NSBI-workflow-tutorial/FAIR_universe_Higgs_tautau/cached_data/
SIGNAL_PROCESSES:
- htautau
BACKGROUND_PROCESSES:
- ttbar
- ztautau
REFERENCE_PROCESSES:
- htautau
- ttbar
PROCESS_TO_INT_LABELS_DICT:
    htautau: 0
    ztautau: 1
    ttbar: 2
TRAINING_FEATURES:
- DER_mass_transverse_met_lep
- log_DER_mass_vis
- log_DER_pt_h
- DER_deltar_had_lep
- log_DER_pt_tot
- log_DER_sum_pt
- DER_pt_ratio_lep_had
- DER_met_phi_centrality
TRAINING_FEATURES_TO_SCALE:
- DER_mass_transverse_met_lep
- log_DER_mass_vis
- log_DER_pt_h
- DER_deltar_had_lep
- log_DER_pt_tot
- log_DER_sum_pt
- DER_pt_ratio_lep_had
- DER_met_phi_centrality
PATH_TO_nominal_DATA: /home/jsandesara_umass_edu/NSBI-workflow-tutorial/FAIR_universe_Higgs_tautau/cached_data/df_nominal.h5
PATH_PRESEL_MODEL: /home/jsandesara_umass_edu/NSBI-workflow-tutorial/FAIR_universe_Higgs_tautau/cached_data/preselection_model/
Regions:
-   Name: CR
    Filter: presel_score<-1.0
    Variable: presel_score
    Binning:
    - -8.747320175170898
    - -6.810490310192108
    - -4.873660445213318
    - -2.9368305802345276
    - -1.0000007152557373
-   Name: SR_binned
    Filter: presel_score>4.5
    Variable: presel_score
    Binning:
    - 4.500021934509277
    - 5.942246437072754
-   Name: SR
    Filter: presel_score>=-1.0 & presel_score<=4.5
    Variable: null
    Binning: null
    TrainedModels:
    -   Name: htautau
        Models: /home/jsandesara_umass_edu/NSBI-workflow-tutorial/FAIR_universe_Higgs_tautau/cached_data/output_training_nominal/output_model_params_htautau/
        Ratios: /home/jsandesara_umass_edu/NSBI-workflow-tutorial/FAIR_universe_Higgs_tautau/cached_data/output_training_nominal/output_ratios_htautau/ratio_htautau.npy
    -   Name: ttbar
        Models: /home/jsandesara_umass_edu/NSBI-workflow-tutorial/FAIR_universe_Higgs_tautau/cached_data/output_training_nominal/output_model_params_ttbar/
        Ratios: /home/jsandesara_umass_edu/NSBI-workflow-tutorial/FAIR_universe_Higgs_tautau/cached_data/output_training_nominal/output_ratios_ttbar/ratio_ttbar.npy
    -   Name: ztautau
        Models: /home/jsandesara_umass_edu/NSBI-workflow-tutorial/FAIR_universe_Higgs_tautau/cached_data/output_training_nominal/output_model_params_ztautau/
        Ratios: /home/jsandesara_umass_edu/NSBI-workflow-tutorial/FAIR_universe_Higgs_tautau/cached_data/output_training_nominal/output_ratios_ztautau/ratio_ztautau.npy
MIX_MODEL_HYPOTHESES:
- htautau
- ttbar
- ztautau
Systematics:
-   Name: TES
    weight_up: /home/jsandesara_umass_edu/NSBI-workflow-tutorial/FAIR_universe_Higgs_tautau/cached_data/df_TES_up.h5
    weight_dn: /home/jsandesara_umass_edu/NSBI-workflow-tutorial/FAIR_universe_Higgs_tautau/cached_data/df_TES_dn.h5
    Type: NormPlusShape
    Samples:
    - htautau
    - ztautau
    - ttbar
-   Name: JES
    weight_up: /home/jsandesara_umass_edu/NSBI-workflow-tutorial/FAIR_universe_Higgs_tautau/cached_data/df_JES_up.h5
    weight_dn: /home/jsandesara_umass_edu/NSBI-workflow-tutorial/FAIR_universe_Higgs_tautau/cached_data/df_JES_dn.h5
    Type: NormPlusShape
    Samples:
    - htautau
    - ztautau
    - ttbar
