# Base path to save/load data from
path_prefix : '/home/jaySandesara/NSBI_workflow_tutorial/FAIR_universe_Higgs_tautau/'

# Cache name
path_saved_data: 'cached_data_new/'

# Directory where pre-selection model is saved
path_preselection_NN_model: 'preselection_saved_NN/'

path_to_nominal_dataframe : f"df_nominal.h5"

# Features to use for training NNs
features : ['DER_mass_transverse_met_lep',
       'log_DER_mass_vis', 'log_DER_pt_h', 'DER_deltar_had_lep', 'log_DER_pt_tot', 'log_DER_sum_pt',
       'DER_pt_ratio_lep_had', 'DER_met_phi_centrality']

# Features to standardize before training
features_scaling : ['DER_mass_transverse_met_lep',
       'log_DER_mass_vis', 'log_DER_pt_h', 'DER_deltar_had_lep', 'log_DER_pt_tot', 'log_DER_sum_pt',
       'DER_pt_ratio_lep_had', 'DER_met_phi_centrality']


# Signal processes in the model
signal_processes : ["htautau"]

# Background processes in the model
background_processes : ["ttbar", "ztautau"]

# choice of reference hypothesis
# ref_processes : ["htautau"] 
ref_processes : ["htautau", "ttbar"] 

# Assign an integer with each of the processes 
labels_dict:
  htautau: 0
  ztautau: 1
  ttbar: 2
  # diboson: 3 # exclude low stats diboson sample for now

# Regions :
#   - Name            : 'SR_binned'
#     Type            : 'binned'
#     Filter          : 'presel_score < '
#     Variable        : ''
#     Binning         : []

#   - Name            : 'CR'
#     Type            : 'binned'
#     Filter          : ''
#     Variable        : ''
#     Binning         : []

#   - Name            : 'SR'
#     Type            : 'unbinned'
#     Filter          : ''

#   - Name: 'CR'
#     Type: 'binned'
#   - Name: 'SR'
#     Type: 'unbinned'

#   Samples :
#     - Name          :
#       SamplePaths     : 'XYZ.h5'
