PATH_PREFIX: /home/jsandesara_umass_edu/NSBI-workflow-tutorial/FAIR_universe_Higgs_tautau/
PATH_SAVED_DATA: /home/jsandesara_umass_edu/NSBI-workflow-tutorial/FAIR_universe_Higgs_tautau/cached_data/
SIGNAL_PROCESSES:
- htautau
BACKGROUND_PROCESSES:
- ttbar
- ztautau
REFERENCE_PROCESSES:
- htautau
- ttbar
PROCESS_TO_INT_LABELS_DICT:
    htautau: 0
    ztautau: 1
    ttbar: 2
TRAINING_FEATURES:
- DER_mass_transverse_met_lep
- log_DER_mass_vis
- log_DER_pt_h
- DER_deltar_had_lep
- log_DER_pt_tot
- log_DER_sum_pt
- DER_pt_ratio_lep_had
- DER_met_phi_centrality
TRAINING_FEATURES_TO_SCALE:
- DER_mass_transverse_met_lep
- log_DER_mass_vis
- log_DER_pt_h
- DER_deltar_had_lep
- log_DER_pt_tot
- log_DER_sum_pt
- DER_pt_ratio_lep_had
- DER_met_phi_centrality
PATH_TO_nominal_DATA: /home/jsandesara_umass_edu/NSBI-workflow-tutorial/FAIR_universe_Higgs_tautau/cached_data/df_nominal.h5
PATH_TO_TES_up_DATA: /home/jsandesara_umass_edu/NSBI-workflow-tutorial/FAIR_universe_Higgs_tautau/cached_data/df_TES_up.h5
PATH_TO_TES_dn_DATA: /home/jsandesara_umass_edu/NSBI-workflow-tutorial/FAIR_universe_Higgs_tautau/cached_data/df_TES_dn.h5
PATH_TO_JES_up_DATA: /home/jsandesara_umass_edu/NSBI-workflow-tutorial/FAIR_universe_Higgs_tautau/cached_data/df_JES_up.h5
PATH_TO_JES_dn_DATA: /home/jsandesara_umass_edu/NSBI-workflow-tutorial/FAIR_universe_Higgs_tautau/cached_data/df_JES_dn.h5
